[build]
  command = "flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_ROOT = "/opt/buildhome/.asdf/installs/flutter/3.24.3-stable"
  FLUTTER_WEB = "true"

[[redirects]]
  from = "/*"
  to = "/index.html" 
  status = 200

[build.processing]
  skip_processing = false
